<?php

declare(strict_types=1);

namespace Alxtexh\Panel\Http\Controllers;

use Alxtexh\Panel\Auth\EmailTwoFactor;
use Alxtexh\Panel\Auth\Mfa;
use Alxtexh\Panel\Auth\Passkeys;
use Alxtexh\Panel\Auth\PasswordPolicy;
use Alxtexh\Panel\Auth\SocialLoginPayload;
use Alxtexh\Panel\Auth\Turnstile;
use Alxtexh\Panel\Auth\TwoFactor;
use Alxtexh\Panel\Notifications\PanelVerifyEmail;
use Alxtexh\Panel\Panel;
use Alxtexh\Panel\PanelManager;
use Alxtexh\Panel\Support\PanelHome;
use Alxtexh\Panel\Support\PanelIdleActivity;
use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Password as PasswordRule;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Signing in to ONE panel, using that panel's own guard.
 *
 * WHY THIS IS NOT FORTIFY. Fortify is excellent and serves exactly one guard:
 * its routes are registered once, at the application root, against
 * `config('fortify.guard')`. A panel generated by `make:panel reseller` has its
 * OWN guard on its OWN path, and there is no second Fortify to give it. So
 * every generated portal meant hand-writing this file, and until somebody did,
 * the first panel page anybody opened died with `Route [login] not defined` -
 * an error that names nothing a newcomer can act on.
 *
 * IT DOES NOT REGISTER `/login`, EVER. The routes live under the panel's prefix
 * (`/reseller/login`), which is what lets this coexist with Breeze, Jetstream
 * or Fortify owning the application's root sign-in rather than fighting it for
 * the URI. A starter kit and a generated portal are then two doors into two
 * guards, which is the honest description of what they are.
 *
 * THE PANEL IS RESOLVED FROM THE ROUTE, not injected, because these actions are
 * mounted per panel by the generated routes file and Laravel gives a controller
 * no idea which group registered it. `panel()` reads the route default that
 * `--auth` writes; getting it wrong is a 404 rather than a wrong-guard sign-in,
 * because an unknown id resolves to null and every action aborts.
 */
final class PanelAuthController extends Controller
{
    public function showLogin(Request $request): Response
    {
        $panel = $this->panel($request);

        return Inertia::render($panel->getLoginComponent(), [
            'action' => $this->url($panel, 'login'),
            'forgotUrl' => $this->passwordsEnabled($panel)
                ? $this->url($panel, 'forgot-password')
                : null,
            'status' => $request->session()->get('status'),
            'heading' => config("panel.auth.{$panel->id}.heading"),
            'description' => config("panel.auth.{$panel->id}.description"),

            /*
             * THE DECISION IS MADE HERE, NOT IN THE COMPONENT, and it is the
             * only reason a prefill is acceptable at all. A Vue file cannot
             * know whether it is running in production; this can. Anything
             * other than `local` gets null, whatever config says.
             */
            'prefill' => app()->environment('local')
                ? config("panel.auth.{$panel->id}.prefill")
                : null,

            /*
             * THE OPTIONAL HALVES OF A SIGN-IN SCREEN, each absent unless the
             * installation actually has it. The reference app's login carried
             * all three and the packaged one carried none, so a generated portal
             * looked plainer than the demo it was copied from - but shipping
             * them ON would be worse: a Turnstile widget with no site key, or a
             * "Sign up" link to a route nobody registered, is a screen that
             * advertises something and then fails.
             */
            'turnstileSiteKey' => $panel->hasTurnstile() ? Turnstile::siteKey() : null,
            'socialProviders' => $this->socialProviders($panel),

            /*
             * PASSKEY SIGN-IN, when `laravel/passkeys` routed it. Null
             * otherwise, and the screen then renders no button - see
             * `Passkeys::signInRoutes()`.
             */
            'passkeys' => Passkeys::signInRoutes(),
            'registerUrl' => $this->registerUrl($panel),
            'magicLinkUrl' => $panel->passwordlessActive()
                ? $this->url($panel, 'magic-link')
                : null,
        ]);
    }

    public function showRegister(Request $request): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('panel/auth/Register', [
            'action' => $this->url($panel, $panel->getRegistrationSlug()),
            'loginUrl' => $this->url($panel, $panel->getLoginSlug()),
            'passwordRules' => PasswordPolicy::complexityHint(PasswordRule::defaults()),
            'turnstileSiteKey' => $panel->hasTurnstile() ? Turnstile::siteKey() : null,
            'heading' => config("panel.auth.{$panel->id}.register_heading"),
            'description' => config("panel.auth.{$panel->id}.register_description"),
        ]);
    }

    public function register(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);
        $model = $this->userModel($panel);

        abort_unless($model !== '' && is_subclass_of($model, Model::class), 404);

        $table = (new $model)->getTable();

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:'.$table.',email'],
            'password' => ['required', 'string', 'confirmed', PasswordRule::defaults()],
        ]);

        $key = Str::transliterate(Str::lower($validated['email']).'|'.$request->ip());
        $max = max(1, (int) config('panel.auth.max_attempts', 5));

        if (RateLimiter::tooManyAttempts($key, $max)) {
            throw ValidationException::withMessages([
                'email' => __('auth.throttle', [
                    'seconds' => $seconds = RateLimiter::availableIn($key),
                    'minutes' => (int) ceil($seconds / 60),
                ]),
            ]);
        }

        $attributes = [
            'name' => $validated['name'],
            'email' => $validated['email'],
            'password' => $validated['password'],
        ];

        if (Schema::hasColumn($table, 'email_verified_at') && ! $panel->hasEmailVerification()) {
            $attributes['email_verified_at'] = now();
        }

        $user = $model::query()->create($attributes);
        abort_unless($user instanceof Authenticatable, 500, 'The configured auth model is not authenticatable.');

        RateLimiter::clear($key);

        Auth::guard($panel->getGuard())->login($user);
        $request->session()->regenerate();
        $request->session()->put('auth.password_confirmed_at', time());

        if ($panel->hasEmailVerification()) {
            Notification::route('mail', (string) $user->getAttribute('email'))->notify(new PanelVerifyEmail($panel));

            return redirect($this->url($panel, 'email/verify'));
        }

        return redirect($this->destination($request, $panel));
    }

    public function showVerifyEmail(Request $request): Response|RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $request->user($panel->getGuard());

        if ($user !== null && ($user->email_verified_at ?? null) !== null) {
            return redirect($this->panelHome($panel));
        }

        return Inertia::render('panel/auth/VerifyEmail', [
            'action' => $this->url($panel, 'email/verification-notification'),
            'logoutUrl' => $this->url($panel, 'logout'),
            'status' => $request->session()->get('status'),
        ]);
    }

    public function sendVerification(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $request->user($panel->getGuard());

        if ($user === null) {
            return redirect($this->url($panel, $panel->getLoginSlug()));
        }

        if (($user->email_verified_at ?? null) !== null) {
            return redirect($this->panelHome($panel));
        }

        Notification::route('mail', $user->email)->notify(new PanelVerifyEmail($panel));

        return back()->with('status', 'verification-link-sent');
    }

    public function verifyEmail(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $request->user($panel->getGuard());

        if ($user === null) {
            return redirect($this->url($panel, $panel->getLoginSlug()));
        }

        if (! hash_equals((string) $request->route('id'), (string) $user->getAuthIdentifier())) {
            abort(403);
        }

        $email = (string) ($user->email ?? '');

        if (! hash_equals((string) $request->route('hash'), sha1($email))) {
            abort(403);
        }

        if (($user->email_verified_at ?? null) === null && Schema::hasColumn($user->getTable(), 'email_verified_at')) {
            $user->forceFill(['email_verified_at' => now()])->save();
        }

        return redirect($this->panelHome($panel));
    }

    /**
     * Sign-in providers, declared by the application.
     *
     * THE URL IS DECLARED RATHER THAN DERIVED. Where a provider redirect lives
     * depends entirely on how that application wired Socialite, and a package
     * that assumed `/auth/{key}/redirect` would send half its consumers to a
     * 404 - a broken button on the one screen nobody can get past.
     *
     * SHAPED AS A LIST, NOT A MAP, because a map's iteration order in JSON is
     * not something to rely on for buttons a person reads left to right.
     *
     * @return list<array{key: string, label: string, url: string, configured: bool, hint: string|null}>
     */
    private function socialProviders(Panel $panel): array
    {
        return SocialLoginPayload::forPanel($panel);
    }

    /**
     * Where "Sign up" goes, if anywhere.
     *
     * NULL IS THE DEFAULT AND THE RIGHT ONE. A panel is a staff tool far more
     * often than a product people join, and a sign-up link on an operator's
     * console is an invitation to create an account nobody approved.
     */
    private function registerUrl(Panel $panel): ?string
    {
        if ($panel->hasRegistration()) {
            return $this->url($panel, $panel->getRegistrationSlug());
        }

        $url = config("panel.auth.{$panel->id}.register");

        return is_string($url) && $url !== '' ? $url : null;
    }

    private function userModel(Panel $panel): string
    {
        $provider = Auth::guard($panel->getGuard())->getProvider();
        $model = method_exists($provider, 'getModel') ? $provider->getModel() : '';

        return is_string($model) ? $model : '';
    }

    /**
     * THE THROTTLE IS THE POINT OF THIS METHOD, more than the credential check.
     *
     * Laravel's `Auth::attempt` will happily be called ten thousand times a
     * minute. The key is the address AND the ip together: keying on the address
     * alone lets anybody lock a colleague out of their own account by failing
     * to sign in as them, and keying on the ip alone lets one office share a
     * budget with an attacker behind the same NAT.
     *
     * THE MESSAGE IS THE SAME FOR A WRONG PASSWORD AND AN UNKNOWN ADDRESS.
     * Distinguishing them turns the form into an account-existence oracle.
     */
    public function login(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        $credentials = $request->validate([
            'email' => ['required', 'string', 'email'],
            'password' => ['required', 'string'],
        ]);

        $key = Str::transliterate(Str::lower($credentials['email']).'|'.$request->ip());
        $max = max(1, (int) config('panel.auth.max_attempts', 5));

        if (RateLimiter::tooManyAttempts($key, $max)) {
            throw ValidationException::withMessages([
                'email' => __('auth.throttle', [
                    'seconds' => $seconds = RateLimiter::availableIn($key),
                    'minutes' => (int) ceil($seconds / 60),
                ]),
            ]);
        }

        $user = $this->userFromCredentials($panel, $credentials);

        if ($user === null) {
            RateLimiter::hit($key, (int) config('panel.auth.decay_seconds', 60));

            throw ValidationException::withMessages([
                'email' => __('auth.failed'),
            ]);
        }

        RateLimiter::clear($key);

        if (Mfa::shouldChallenge($panel, $user)) {
            return Mfa::begin($request, $panel, $user, $request->boolean('remember'));
        }

        Mfa::complete($request, $panel, $user, $request->boolean('remember'));

        return redirect($this->destination($request, $panel));
    }

    /**
     * The TOTP / recovery pause. Not skippable: there is no "remember this
     * browser" bypass. A missing pending login sends them back to the form.
     */
    public function showTwoFactorChallenge(Request $request): Response|RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $this->challengedUser($request, $panel);

        if ($user === null) {
            return redirect($this->url($panel, 'login'));
        }

        return Inertia::render('panel/auth/TwoFactorChallenge', [
            'action' => $this->url($panel, 'two-factor-challenge'),
            'method' => EmailTwoFactor::method($request),
            'resendUrl' => EmailTwoFactor::method($request) === EmailTwoFactor::METHOD_EMAIL
                ? $this->url($panel, 'two-factor-challenge/email')
                : null,
            'sentTo' => EmailTwoFactor::method($request) === EmailTwoFactor::METHOD_EMAIL
                ? EmailTwoFactor::maskedAddress($user)
                : null,
            'status' => $request->session()->get('status'),
            'turnstileSiteKey' => $panel->hasTurnstile() ? Turnstile::siteKey() : null,
        ]);
    }

    public function resendEmailTwoFactor(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $this->challengedUser($request, $panel);

        if ($user === null) {
            return redirect($this->url($panel, 'login'));
        }

        if (! EmailTwoFactor::enabled($user)) {
            return redirect($this->url($panel, 'two-factor-challenge'));
        }

        EmailTwoFactor::send($request, $user);

        return back()->with('status', 'A new code is on its way.');
    }

    public function twoFactorChallenge(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);
        $user = $this->challengedUser($request, $panel);

        if ($user === null) {
            return redirect($this->url($panel, 'login'));
        }

        $key = 'two-factor|'.$user->getAuthIdentifier().'|'.$request->ip();
        $max = max(1, (int) config('panel.auth.max_attempts', 5));

        if (RateLimiter::tooManyAttempts($key, $max)) {
            throw ValidationException::withMessages([
                'code' => __('auth.throttle', [
                    'seconds' => $seconds = RateLimiter::availableIn($key),
                    'minutes' => (int) ceil($seconds / 60),
                ]),
            ]);
        }

        $code = (string) $request->input('code', '');
        $recovery = (string) $request->input('recovery_code', '');
        $method = EmailTwoFactor::method($request);

        if ($method === EmailTwoFactor::METHOD_EMAIL) {
            if (! EmailTwoFactor::verify($request, $code)) {
                RateLimiter::hit($key, (int) config('panel.auth.decay_seconds', 60));

                throw ValidationException::withMessages([
                    'code' => __('The provided two factor authentication code was invalid.'),
                ]);
            }
        } elseif ($recovery !== '') {
            $matched = TwoFactor::verifyRecovery($user, $recovery);

            if ($matched === null) {
                RateLimiter::hit($key, (int) config('panel.auth.decay_seconds', 60));

                throw ValidationException::withMessages([
                    'recovery_code' => __('The provided two factor authentication code was invalid.'),
                ]);
            }

            TwoFactor::consumeRecovery($user, $matched);
        } elseif (! TwoFactor::verifyCode($user, $code)) {
            RateLimiter::hit($key, (int) config('panel.auth.decay_seconds', 60));

            throw ValidationException::withMessages([
                'code' => __('The provided two factor authentication code was invalid.'),
            ]);
        }

        RateLimiter::clear($key);

        $remember = TwoFactor::remember($request);
        Mfa::complete($request, $panel, $user, $remember);

        return redirect($this->destination($request, $panel));
    }

    /**
     * WHERE SIGNING IN LANDS YOU, and it must be inside the portal you signed
     * in to.
     *
     * `url.intended` IS ONE SESSION KEY SHARED BY EVERY PANEL, which is the
     * bug this method exists for. Laravel's `Authenticate` middleware writes it
     * whenever a guest is turned away from a guarded page - so opening
     * `/dashboard`, being bounced to the demo's sign-in, then going to
     * `/superadmin/login` and authenticating there popped `/dashboard` and
     * landed you in the OTHER portal. On a different guard, holding no session
     * there, so that page bounced you straight back out to a login screen.
     *
     * The symptom reads as "the panels are not separated" and the separation
     * was fine: the guards, the tables and the sessions were all correct, and
     * one shared session key sent you to the wrong building anyway.
     *
     * SO AN INTENDED URL IS HONOURED ONLY WHEN IT BELONGS TO THIS PANEL.
     * Ownership is decided by the longest matching path, because a panel at the
     * ROOT would otherwise claim every URL including the other portals' - the
     * demo mounts its operator panel at `/` and would swallow `/superadmin/…`
     * on that test alone.
     *
     * A FOREIGN URL IS FORGOTTEN RATHER THAN LEFT, or it sits in the session
     * waiting to misdirect the next sign-in instead of this one.
     */
    private function destination(Request $request, Panel $panel): string
    {
        $intended = $request->session()->pull('url.intended');

        if (! is_string($intended) || $intended === '') {
            return $this->panelHome($panel);
        }

        $path = '/'.ltrim((string) parse_url($intended, PHP_URL_PATH), '/');

        if (PanelIdleActivity::isLockScreenPath($path)) {
            return $this->panelHome($panel);
        }

        return $this->panelOwning($path)?->id === $panel->id
            ? $intended
            : $this->panelHome($panel);
    }

    /**
     * Which panel a path belongs to - the LONGEST matching prefix wins.
     *
     * A panel mounted at `/` matches everything, so a plain `str_starts_with`
     * over an unordered list answers "the root panel" for `/superadmin/help`
     * depending only on registration order.
     */
    private function panelOwning(string $path): ?Panel
    {
        $best = null;
        $bestLength = -1;

        foreach (app(PanelManager::class)->panels() as $candidate) {
            $prefix = '/'.trim($candidate->getPath(), '/');

            $matches = $prefix === '/'
                ? true
                : ($path === $prefix || str_starts_with($path, rtrim($prefix, '/').'/'));

            if ($matches && strlen($prefix) > $bestLength) {
                $best = $candidate;
                $bestLength = strlen($prefix);
            }
        }

        return $best;
    }

    /**
     * INVALIDATE AND RE-TOKEN, not just `logout()`.
     *
     * `Auth::logout` forgets the user and leaves the session row intact, so
     * everything else written into it - a cart, a wizard's progress, a flash
     * message meant for somebody else - survives into the next person's visit
     * on a shared machine. Regenerating the CSRF token matters for the same
     * reason: the old one is still valid otherwise.
     */
    public function logout(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        Auth::guard($panel->getGuard())->logout();

        PanelIdleActivity::clearLock($request);
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect($this->url($panel, 'login'));
    }

    public function showForgotPassword(Request $request): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('panel/auth/ForgotPassword', [
            'action' => $this->url($panel, 'forgot-password'),
            'loginUrl' => $this->url($panel, 'login'),
            'status' => $request->session()->get('status'),
            'turnstileSiteKey' => $panel->hasTurnstile() ? Turnstile::siteKey() : null,
        ]);
    }

    /**
     * ONE ANSWER FOR A HIT AND A MISS, deliberately.
     *
     * Laravel's broker returns distinct statuses and it is tempting to render
     * them, because "we have no account with that address" is genuinely more
     * helpful. It is also an account-existence oracle: one address at a time,
     * anybody can learn who your customers are. The link is sent or it is not,
     * and the screen says the same thing either way.
     */
    public function sendResetLink(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        $request->validate(['email' => ['required', 'string', 'email']]);

        /*
         * THE PORTAL'S BROKER, NOT THE APPLICATION'S - see
         * `Panel::passwordBroker()`.
         *
         * THIS USED TO READ ONE GLOBAL KEY and it was a real hole, not a
         * tidiness point. A broker names a PROVIDER, which names a TABLE, so
         * `panel.auth.broker` = `users` meant a CUSTOMER asking the client
         * portal for a reset had their address looked up among OPERATORS -
         * finding nobody on a good day, and on a bad one mailing a working
         * reset link for an operator account that happened to share the
         * address. Two guards and one broker cannot be right.
         */
        Password::broker($panel->getPasswordBroker())->sendResetLink(
            $request->only('email'),
        );

        return back()->with(
            'status',
            __('If that address has an account, a reset link is on its way.'),
        );
    }

    public function showResetPassword(Request $request, string $token): Response
    {
        $panel = $this->panel($request);

        return Inertia::render('panel/auth/ResetPassword', [
            'action' => $this->url($panel, 'reset-password'),
            'token' => $token,
            'email' => (string) $request->query('email', ''),
        ]);
    }

    public function resetPassword(Request $request): RedirectResponse
    {
        $panel = $this->panel($request);

        $request->validate([
            'token' => ['required', 'string'],
            'email' => ['required', 'string', 'email'],
            'password' => ['required', 'string', 'confirmed', 'min:8'],
        ]);

        $status = Password::broker($panel->getPasswordBroker())->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'),
            /*
             * THE REMEMBER TOKEN GOES WITH THE PASSWORD, and this is the path
             * where forgetting it matters most.
             *
             * A password reset is what somebody does when they have LOST
             * control of the account. `SessionGuard` re-authenticates from a
             * "remember me" recaller cookie whenever the session is missing,
             * and it validates only `remember_token` - so an attacker holding a
             * stolen recaller kept the account straight through the reset,
             * because the one credential they were using was the one nothing
             * changed.
             *
             * `event(new PasswordReset(...))` is Laravel's own signal that this
             * happened; nothing in the package listened, and an installation
             * that wants to notify or audit needs it fired.
             */
            static function ($user, string $password): void {
                $user->forceFill([
                    'password' => bcrypt($password),
                    'remember_token' => Str::random(60),
                ])->save();

                event(new PasswordReset($user));
            },
        );

        if ($status !== Password::PASSWORD_RESET) {
            throw ValidationException::withMessages(['email' => __($status)]);
        }

        return redirect($this->url($panel, 'login'))->with('status', __($status));
    }

    /* ------------------------------------------------------------- helpers */

    /**
     * Retrieve and check the password WITHOUT logging in.
     *
     * `Auth::attempt` would create the session before the TOTP pause, which is
     * the bug this method exists to avoid. Fortify's login pipeline does the
     * same split: credentials first, then either a challenge or a login.
     */
    /** @param array<string, mixed> $credentials */
    private function userFromCredentials(Panel $panel, array $credentials): ?Authenticatable
    {
        $provider = Auth::guard($panel->getGuard())->getProvider();
        $user = $provider->retrieveByCredentials($credentials);

        if ($user === null || ! $provider->validateCredentials($user, ['password' => $credentials['password']])) {
            return null;
        }

        if (config('hashing.rehash_on_login', true)) {
            $provider->rehashPasswordIfRequired($user, ['password' => $credentials['password']]);
        }

        return $user;
    }

    private function challengedUser(Request $request, Panel $panel): ?Authenticatable
    {
        $provider = Auth::guard($panel->getGuard())->getProvider();
        $model = method_exists($provider, 'getModel') ? $provider->getModel() : '';

        if (! is_string($model) || $model === '') {
            return null;
        }

        $user = TwoFactor::challengedUser($request, $model);

        if ($user === null) {
            return null;
        }

        $pendingPanel = TwoFactor::panelId($request);

        if ($pendingPanel !== null && $pendingPanel !== $panel->id) {
            return null;
        }

        return $user;
    }

    /**
     * WHICH PANEL THIS REQUEST BELONGS TO.
     *
     * From a route default rather than a segment: a panel mounted at the root
     * has no segment to read, and one mounted at `/admin/staff` has two.
     * `--auth` writes `->defaults('panel', $id)` on the group.
     */
    private function panel(Request $request): Panel
    {
        $id = (string) $request->route()?->defaults['panel'];

        $panel = app(PanelManager::class)->panel($id);

        abort_if($panel === null, 404);

        return $panel;
    }

    /** A URL inside the panel's own prefix. */
    private function url(Panel $panel, string $path): string
    {
        return '/'.trim(trim($panel->getPath(), '/').'/'.$path, '/');
    }

    /**
     * Where a signed-in person lands - the dashboard, or the panel's root.
     *
     * Deliberately not a named route: a generated portal's route names belong
     * to the application. See `PanelHome` for why the root alone was wrong.
     */
    private function panelHome(Panel $panel): string
    {
        return PanelHome::urlFor($panel);
    }

    /**
     * Whether the reset pair was routed.
     *
     * OFF UNLESS THE APPLICATION CAN SEND MAIL, which `--auth` asks about,
     * because a "Forgot password?" link that leads to a form that silently
     * queues a mail nobody delivers is worse than no link: somebody waits.
     */
    /**
     * THE PANEL IS ASKED FIRST, then config.
     *
     * A PORTAL THAT DECLARED `passwordReset(false)` STILL RENDERED THE LINK,
     * because this read config alone - so the panel object said one thing, the
     * routes were not registered accordingly, and the screen offered a
     * "Forgot password?" that 404ed. Config remains the answer for a portal
     * whose routes come from a hand-written `panel-{id}-auth.php`, which has
     * no panel-level declaration to read.
     */
    private function passwordsEnabled(Panel $panel): bool
    {
        return $panel->hasPasswordReset()
            && (bool) config("panel.auth.{$panel->id}.passwords", true);
    }
}
