<?php

declare(strict_types=1);

namespace App\Panel\Client\Resources;

use App\Models\Plan;
use Alxtexh\Panel\Actions\RecordAction;
use Alxtexh\Panel\Resources\Resource;
use Alxtexh\Panel\Tables\Columns\BadgeColumn;
use Alxtexh\Panel\Tables\Columns\DateColumn;
use Alxtexh\Panel\Tables\Columns\TextColumn;
use Alxtexh\Panel\Tables\Table;

/**
 * Generated by `make:panel-resource Plan`.
 *
 * Edit freely - this is a starting point, not a contract. Discovery picks
 * it up automatically, so there is nothing to register.
 *
 * `tenant_id` is deliberately absent from the form. It is set from request
 * context, and a field for it would be a way to write into another tenant.
 */
final class PlanResource extends Resource
{
    protected static string $model = Plan::class;

    /*
     * WHICH PANEL THIS BELONGS TO, and therefore where it is reachable.
     * Only this panel's routes resolve it: a resource is not visible -
     * or addressable - from another portal, which is the isolation the
     * panel split exists for rather than a naming convention.
     */
    protected static string $panel = 'client';

    /*
     * EVERY RESOURCE MUST DECLARE ONE, and `make:panel-resource` did not write
     * it - a convention test caught the omission the first time the suite ran.
     */
    protected static ?string $purpose = 'The plans available on your account, to compare before asking to change.';

    /**
     * `client-plans`, NOT `plans` - AND THE GENERATOR DID NOT DO THIS FOR ME.
     *
     * `make:panel-resource Plan --panel=client --generate` derived the key from
     * the model, produced `plans`, and printed "Visit /client/plans - no
     * registration needed". The admin panel already owns `plans`, so the next
     * request threw and the WHOLE APPLICATION was down - every panel, not just
     * this one.
     *
     * The framework's own message is exact and actionable ("Two resources both
     * use the key [plans] ... Override `key()` on one of them"), which is why
     * this was a two-minute fix rather than an afternoon. But a generator that
     * hands you a broken application and reports success is doing the one thing
     * a generator must not: it is faster than writing the file by hand and
     * wrong in a way you only discover by running the app.
     *
     * Keys are GLOBALLY unique, not per panel, because they are URL segments
     * and ability names - `view_any_plans` cannot mean two different things.
     * `Reseller\PlanResource` solved this the same way, by hand, for the same
     * reason.
     */
    public static function key(): string
    {
        return 'client-plans';
    }

    /*
     * NO `form()`, AND THE GENERATOR WROTE ONE.
     *
     * It produced an editable form over every column - name, speed, price -
     * because it reads the TABLE and cannot know who the panel is for. On a
     * customer portal that is a create button leading to a screen `PlanPolicy`
     * refuses, which is a 403 an operator has to explain rather than a feature.
     *
     * A resource with no form is read-only: no create, no edit, and nothing to
     * import into. The refusal still lives in the policy - a resource is a
     * screen and a policy is the boundary - but the screen no longer offers
     * what the boundary will decline.
     */

    public static function table(Table $table): Table
    {
        return $table
            // Browsed, then opened - see ClientResource's own note on why
            // this is declared per resource rather than default. rowClick
            // alone only arms the click; the row still needs a real 'view'
            // RecordAction below to have somewhere to send it.
            ->rowClick('view')
            ->recordActions([
                RecordAction::make('view', 'View')
                    ->icon('eye')
                    ->color('primary')
                    ->authorize('view')
                    ->link(fn (array $row): string => '/client/client-plans/'.$row['id']),
            ])
            ->columns([
                TextColumn::make('name')->from('plans.name')->sortable()->searchable()->locked(),
                TextColumn::make('speed_mbps')->from('plans.speed_mbps')->sortable(),
                TextColumn::make('price_cents')->from('plans.price_cents')->sortable(),
                BadgeColumn::make('is_active')->from('plans.is_active')->colors(['1' => 'success', '' => 'neutral']),
                DateColumn::make('created_at')->from('plans.created_at')->sortable()->withTime()->muted(),
                DateColumn::make('updated_at')->from('plans.updated_at')->sortable()->withTime()->muted(),
                TextColumn::make('position')->from('plans.position')->sortable(),
                TextColumn::make('custom')->from('plans.custom')->muted(),
            ])
            ->keyColumn('plans.id')
            ->alsoSelect(['plans.id'])
            /*
             * ROW AND BULK ACTIONS ARE NOT GENERATED, because what may
             * be DONE to a Plan is the one thing a table cannot be
             * read off. Uncomment into this chain and edit:
             *
             * ->recordActions([
             *     RecordAction::make('suspend', 'Suspend')
             *         ->authorize('update')
             *         ->confirm('Suspend this Plan?')
             *         ->mutate(['status' => 'suspended']),
             *
             *     // ASKING FOR SOMETHING FIRST is `->form()`. The modal
             *     // opens with no request - the schema travels with the
             *     // action - so do NOT write a screen for this.
             *     RecordAction::make('note', 'Add a note')
             *         ->authorize('update')
             *         ->form(fn (Form $form): Form => $form->schema([
             *             TextareaField::make('note')->required()->rule('max:280'),
             *         ]))
             *         ->handle(fn (Plan $record, array $data) => $record
             *             ->notes()->create($data)),
             * ])
             * ->bulkActions([
             *     // The same `->form()` works here and is asked ONCE for
             *     // the whole selection; the handler runs once per chunk
             *     // with the same values.
             *     BulkAction::make('suspend', 'Suspend selected')
             *         ->authorize('update')
             *         ->mutate(['status' => 'suspended']),
             * ])
             *
             * `->form()` PAIRS WITH `->handle()`, NEVER `->mutate()` - a
             * mutation is fixed at definition time and has nowhere to
             * put what somebody typed, and declaring both throws. The
             * declared FIELDS are the allow-list: the endpoint validates
             * against them and drops every key they do not name.
             *
             * `->authorize()` NAMES A POLICY METHOD, and an action
             * without one is refused rather than permitted.
             *
             * IMPORT WHAT YOU UNCOMMENT - they are not imported above,
             * because an import for code nobody wrote yet is one every
             * linter deletes:
             *
             *     use Alxtexh\Panel\Actions\BulkAction;
             *     use Alxtexh\Panel\Actions\RecordAction;
             *                  */
            ->defaultSort('created_at', 'desc');
    }
}
