<?php

declare(strict_types=1);

namespace App\Panel\Platform\Resources;

use App\Models\Tenant;
use Alxtexh\Panel\Actions\RecordAction;
use Alxtexh\Panel\Forms\Fields\DateField;
use Alxtexh\Panel\Forms\Fields\TextareaField;
use Alxtexh\Panel\Forms\Fields\TextField;
use Alxtexh\Panel\Forms\Form;
use Alxtexh\Panel\Resources\Resource;
use Alxtexh\Panel\Tables\Columns\DateColumn;
use Alxtexh\Panel\Tables\Columns\TextColumn;
use Alxtexh\Panel\Tables\Table;

/**
 * Generated by `make:panel-resource Tenant`.
 *
 * Edit freely - this is a starting point, not a contract. Discovery picks
 * it up automatically, so there is nothing to register.
 *
 * `tenant_id` is deliberately absent from the form. It is set from request
 * context, and a field for it would be a way to write into another tenant.
 */
final class TenantResource extends Resource
{
    protected static string $model = Tenant::class;

    protected static ?string $purpose = 'Every organisation on this installation, and their status.';

    /*
     * WHICH PANEL THIS BELONGS TO, and therefore where it is reachable.
     * Only this panel's routes resolve it: a resource is not visible -
     * or addressable - from another portal, which is the isolation the
     * panel split exists for rather than a naming convention.
     */
    protected static string $panel = 'platform';

    public static function form(Form $form): Form
    {
        return $form->columns(2)->schema([
            TextField::make('name')->required(),
            TextField::make('slug')->required(),
            TextField::make('logo_url'),
            TextareaField::make('theme_colors'),
            TextareaField::make('features'),
            TextField::make('logo_path'),
            TextField::make('tenancy_db_name'),
            TextField::make('locale'),
            DateField::make('suspended_at')->withTime(),
            TextField::make('suspended_reason'),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            // Browsed, then opened - see ClientResource's own note on why
            // this is declared per resource rather than default. rowClick
            // alone only arms the click; the row still needs a real 'view'
            // RecordAction below to have somewhere to send it.
            ->rowClick('view')
            ->recordActions([
                RecordAction::make('view', 'View')
                    ->icon('eye')
                    ->color('primary')
                    ->authorize('view')
                    ->link(fn (array $row): string => '/platform/tenants/'.$row['id']),
            ])
            ->columns([
                TextColumn::make('name')->from('tenants.name')->sortable()->searchable()->locked(),
                TextColumn::make('slug')->from('tenants.slug')->sortable()->searchable(),
                TextColumn::make('logo_url')->from('tenants.logo_url')->sortable()->searchable(),
                TextColumn::make('theme_colors')->from('tenants.theme_colors')->muted(),
                TextColumn::make('features')->from('tenants.features')->muted(),
                DateColumn::make('created_at')->from('tenants.created_at')->sortable()->withTime()->muted(),
                DateColumn::make('updated_at')->from('tenants.updated_at')->sortable()->withTime()->muted(),
                TextColumn::make('logo_path')->from('tenants.logo_path')->sortable()->searchable(),
                TextColumn::make('tenancy_db_name')->from('tenants.tenancy_db_name')->sortable()->searchable(),
                TextColumn::make('locale')->from('tenants.locale')->sortable()->searchable(),
                DateColumn::make('suspended_at')->from('tenants.suspended_at')->sortable()->withTime(),
                TextColumn::make('suspended_reason')->from('tenants.suspended_reason')->sortable()->searchable(),
            ])
            ->keyColumn('tenants.id')
            ->alsoSelect(['tenants.id'])
            ->defaultSort('created_at', 'desc');
    }
}
