<?php

declare(strict_types=1);

namespace Alxtexh\Panel\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Alxtexh\Panel\PanelManager;

/**
 * php artisan make:panel-resource {Model} [--generate]
 *
 * `--generate` is the whole point of the command. Introspecting the table and
 * mapping column types to sensible defaults is what turns a thirty-minute task
 * into a thirty-second one (spec §7), and combined with filesystem discovery it
 * means the generated class is routable and rendering with NO hand editing.
 *
 * The generated file is a starting point, not a contract. It is meant to be
 * edited - which is why it is written as ordinary readable PHP rather than
 * something clever.
 */
final class MakeResourceCommand extends Command
{
    protected $signature = 'make:panel-resource
                            {model : The Eloquent model class name, e.g. Invoice}
                            {--panel= : Which panel it belongs to. Defaults to the first registered one}
                            {--generate : Introspect the table and pre-fill columns and fields}
                            {--force : Overwrite an existing resource}';

    protected $description = 'Create a panel resource';

    /**
     * Never shown and never writable.
     *
     * `tenant_id` above all: it is set from request context, and a generated
     * form field for it would be a way to move a record into another tenant.
     *
     * @var list<string>
     */
    private const HIDDEN = ['id', 'tenant_id', 'deleted_at', 'remember_token', 'password'];

    /**
     * Shown on the table but never on the form.
     *
     * Timestamps are what operators sort by, so excluding them from the table
     * entirely was wrong - and it also produced a class that threw on load,
     * because the generated `defaultSort('created_at')` referenced a column no
     * generated column declared, so it was not in the sortable allowlist.
     *
     * @var list<string>
     */
    private const READ_ONLY = ['created_at', 'updated_at'];

    public function handle(): int
    {
        $model = Str::studly($this->argument('model'));
        $modelClass = "App\\Models\\{$model}";

        if (! class_exists($modelClass)) {
            /*
             * THE WAY OUT IS PART OF THE ERROR, because this is the first
             * command a new installation runs and being told only what is wrong
             * leaves somebody guessing at their own second step.
             *
             * A resource is built BY READING THE TABLE - the columns become the
             * table's columns and the form's fields - so the model and its
             * migration have to exist first. That ordering is obvious once you
             * know it and invisible before, and the README used to skip it
             * entirely: it went straight from `panel:install` to this command,
             * so following the documentation exactly produced this error.
             */
            $this->components->error("Model [{$modelClass}] does not exist.");

            $this->components->bulletList([
                "php artisan make:model {$model} -m   - create it, with a migration",
                'Fill the migration in, then run php artisan migrate',
                "php artisan {$this->getName()} {$model} --generate   - then come back here",
            ]);

            $this->components->info(
                'A resource is generated by reading the table, so the columns have to exist first.'
            );

            return self::FAILURE;
        }

        /*
         * WHICH PANEL, AND THEREFORE WHICH DIRECTORY AND NAMESPACE.
         *
         * A resource is only routable from the panel it declares, so putting one
         * in the wrong place produces a class that discovery finds, the registry
         * holds, and no URL reaches - an empty menu entry that never appears and
         * nothing to explain why. Asking makes the decision explicit at the one
         * moment somebody knows the answer.
         */
        [$panelId, $directory, $namespace] = $this->panelTarget();

        $path = $directory."/{$model}Resource.php";

        if (file_exists($path) && ! $this->option('force')) {
            $this->components->error("Resource already exists: {$path}. Use --force to overwrite.");

            return self::FAILURE;
        }

        $table = (new $modelClass)->getTable();

        $generated = $this->option('generate')
            ? $this->introspect($table, $modelClass)
            : $this->placeholders();

        $columns = $generated['columns'];
        $fields = $generated['fields'];
        $filters = $generated['filters'];
        $imports = $generated['imports'];
        $softDeletes = $generated['softDeletes'];
        $hasMany = $generated['hasMany'];

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        file_put_contents($path, $this->render(
            $model,
            $modelClass,
            $columns,
            $fields,
            $filters,
            $imports,
            $panelId,
            $namespace,
            $softDeletes,
            $hasMany,
        ));

        $this->components->info("Created {$path}");

        $this->writePolicy($model, $modelClass);
        $this->writeFactory($model, $modelClass);
        $this->writeContractTest($model, $modelClass, $namespace);

        if ($this->option('generate')) {
            /*
             * THE PANEL'S OWN PATH, not a bare `/plans`. A resource generated
             * into a second portal is reachable at that portal's prefix, and a
             * message naming the root sends somebody to a 404 and then to the
             * routing code looking for a bug that is not there.
             */
            $prefix = trim((string) app(PanelManager::class)->panel($panelId)?->getPath(), '/');
            $url = '/'.($prefix === '' ? '' : $prefix.'/').Str::of($model)->plural()->kebab();

            $this->components->info("Introspected [{$table}]. Visit {$url} - no registration needed.");
        }

        return self::SUCCESS;
    }

    /**
     * Which panel this resource is for, and where its class goes.
     *
     * THE FIRST REGISTERED PANEL IS THE DEFAULT, not a literal `'admin'`. An
     * application that renamed its only panel would otherwise get resources
     * declaring a panel that does not exist - discovered, registered, and
     * reachable from nowhere, with no error anywhere.
     *
     * @return array{0: string, 1: string, 2: string} panel id, directory, namespace
     */
    private function panelTarget(): array
    {
        $panels = app(PanelManager::class)->panels();
        $requested = $this->option('panel');

        /*
         * THE CONFIGURED DEFAULT PANEL, not whichever happens to be first in the
         * array. Provider order is decided by a file that a generator edits, so
         * "first" silently changed every time a portal was created - and with it
         * where the next resource was written.
         */
        $default = (string) config('panel.default', 'admin');

        $id = $requested !== null ? (string) $requested : $default;

        /*
         * A PANEL THAT IS NOT REGISTERED IS A TYPO, and generating into it would
         * produce a class nothing ever routes. Naming the ones that do exist
         * turns a silent dead end into a one-line correction.
         */
        if ($requested !== null && ! array_key_exists($id, $panels)) {
            $known = $panels === [] ? 'none are registered' : implode(', ', array_keys($panels));

            throw new \RuntimeException("No panel [{$id}]. Registered: {$known}.");
        }

        /*
         * THE FIRST PANEL KEEPS THE ORIGINAL LOCATION. Its resources are already
         * at `app/Panel/Resources`, and moving them to satisfy a naming scheme
         * would be a rename with no benefit and a broken discovery config for
         * anybody who had customised it.
         */
        if ($id === $default) {
            return [$id, app_path('Panel/Resources'), 'App\\Panel\\Resources'];
        }

        $studly = Str::studly($id);

        return [$id, app_path("Panel/{$studly}/Resources"), "App\\Panel\\{$studly}\\Resources"];
    }

    /**
     * A policy stub, because the panel DENIES an ability whose model has no
     * policy.
     *
     * Without this the generator would produce a resource that renders an empty
     * table with no actions and no explanation - technically secure, and a
     * broken promise, since --generate is supposed to need no hand editing.
     *
     * The stub is deliberately permissive-within-tenant and clearly marked, so
     * the decision is visible and editable rather than implied.
     */
    private function writePolicy(string $model, string $modelClass): void
    {
        $path = app_path("Policies/{$model}Policy.php");

        if (file_exists($path)) {
            return;
        }

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $stub = <<<PHP
        <?php

        declare(strict_types=1);

        namespace App\\Policies;

        use Alxtexh\\Panel\\Policies\\TenantResourcePolicy;

        /**
         * Generated alongside {$model}Resource.
         *
         * THE BASE CLASS IS THE POLICY. It answers two questions in order -
         * is this record yours, and does your role permit the action - and
         * denies unless both pass. Ability names are derived from the
         * resource key, so `view_any_*` and friends exist without anything
         * being written down.
         *
         * NOTHING IS PERMITTED UNTIL PERMISSIONS ARE SYNCED:
         *
         *     php artisan panel:permissions sync
         *
         * That is the correct direction. A policy that granted everything
         * until edited is one somebody forgets to edit, and forgetting is
         * silent.
         *
         * TO ADD A RULE, override a method - and use the base class's
         * parameter type exactly:
         *
         *     public function delete(Authenticatable&Authorizable \$user, ?Model \$record = null): bool
         *
         * PHP forbids narrowing that to your own `User`, and doing so is a
         * fatal thrown while the class loads rather than a readable error.
         */
        final class {$model}Policy extends TenantResourcePolicy {}

        PHP;

        file_put_contents($path, $stub);

        $this->components->info("Created {$path}");
        $this->components->info("{$model}Policy denies until `panel:permissions sync` grants the abilities.");
    }

    private function writeFactory(string $model, string $modelClass): void
    {
        $path = database_path("factories/{$model}Factory.php");

        if (file_exists($path)) {
            return;
        }

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $stub = <<<PHP
        <?php

        declare(strict_types=1);

        namespace Database\Factories;

        use {$modelClass};
        use Illuminate\Database\Eloquent\Factories\Factory;

        /** @extends Factory<{$model}> */
        class {$model}Factory extends Factory
        {
            protected $model = {$model}::class;

            /**
             * Add domain-safe defaults here. The empty definition is deliberate:
             * guessing required business fields would create invalid fixtures.
             *
             * @return array<string, mixed>
             */
            public function definition(): array
            {
                return [];
            }
        }

        PHP;

        file_put_contents($path, $stub);
        $this->components->info("Created {$path}");
    }

    private function writeContractTest(string $model, string $modelClass, string $namespace): void
    {
        $path = base_path("tests/Feature/Panel/{$model}ResourceTest.php");

        if (file_exists($path)) {
            return;
        }

        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        $resourceClass = "{$namespace}\\{$model}Resource";
        $stub = <<<PHP
        <?php

        declare(strict_types=1);

        namespace Tests\Feature\Panel;

        use {$modelClass};
        use {$resourceClass};
        use Tests\TestCase;

        final class {$model}ResourceTest extends TestCase
        {
            public function test_the_generated_resource_exposes_a_model_and_table_schema(): void
            {
                self::assertSame({$model}::class, {$model}Resource::model());
                self::assertNotEmpty({$model}Resource::definition()->getColumns());
            }
        }

        PHP;

        file_put_contents($path, $stub);
        $this->components->info("Created {$path}");
    }

    /**
     * Map real database columns to columns, fields, and filters.
     *
     * @return array{
     *     columns: list<string>,
     *     fields: list<string>,
     *     filters: list<string>,
     *     imports: list<string>,
     *     softDeletes: bool,
     *     hasMany: list<string>
     * }
     */
    private function introspect(string $table, string $modelClass): array
    {
        $columns = [];
        $fields = [];
        $filters = [];
        $imports = [];
        $softDeletes = Schema::hasColumn($table, 'deleted_at');
        $model = new $modelClass;
        $casts = method_exists($model, 'getCasts') ? $model->getCasts() : [];

        foreach (Schema::getColumns($table) as $column) {
            $name = $column['name'];

            if (in_array($name, self::HIDDEN, true)) {
                continue;
            }

            $readOnly = in_array($name, self::READ_ONLY, true);

            $type = strtolower((string) ($column['type_name'] ?? $column['type'] ?? 'string'));
            $rawType = strtolower((string) ($column['type'] ?? $type));
            $nullable = (bool) ($column['nullable'] ?? true);
            $qualified = "{$table}.{$name}";
            $required = $nullable ? '' : '->required()';
            $enumOptions = $this->enumOptions($name, $rawType, $casts);

            if (str_ends_with($name, '_at') || in_array($type, ['date', 'datetime', 'timestamp'], true)) {
                $withTime = ! str_starts_with($type, 'date') || str_contains($type, 'time');
                $columns[] = "DateColumn::make('{$name}')->from('{$qualified}')->sortable()"
                    .($withTime ? '->withTime()' : '').($readOnly ? '->muted()' : '');
                $imports['DateColumn'] = 'Columns\DateColumn';

                if (! $readOnly) {
                    $fields[] = "DateField::make('{$name}'){$required}".($withTime ? '->withTime()' : '');
                    $imports['DateField'] = 'Fields\DateField';
                }

                if (! $readOnly && ! in_array($name, ['created_at', 'updated_at'], true)) {
                    $filters[] = "DateRangeFilter::make('{$name}')->column('{$qualified}')";
                    $imports['DateRangeFilter'] = 'Filters\DateRangeFilter';
                }

                continue;
            }

            if (str_ends_with($name, '_id')) {
                $related = $this->inferRelatedModel($name);

                if ($related !== null) {
                    $title = $this->inferTitleAttribute($related);
                    $short = class_basename($related);
                    $columns[] = "TextColumn::make('{$name}')->from('{$qualified}')->sortable()->muted()";
                    $fields[] = "SelectField::make('{$name}'){$required}"
                        ."->relationship({$short}::class, '{$title}')";
                    $imports['TextColumn'] = 'Columns\TextColumn';
                    $imports['SelectField'] = 'Fields\SelectField';
                    $imports[$short] = "Models\\{$short}";

                    continue;
                }

                $columns[] = "TextColumn::make('{$name}')->from('{$qualified}')->muted()";
                $fields[] = "/* No model matching this foreign key was discovered. "
                    ."Replace the empty options with a scoped query, or use "
                    ."->relationship(RelatedModel::class, 'title'). */\n            "
                    ."SelectField::make('{$name}'){$required}->options([])";
                $imports['TextColumn'] = 'Columns\TextColumn';
                $imports['SelectField'] = 'Fields\SelectField';

                continue;
            }

            if ($enumOptions !== []) {
                $this->appendEnumColumn($columns, $fields, $filters, $imports, $name, $qualified, $required, $enumOptions);

                continue;
            }

            if ($this->isLikelyEnumColumn($name, $type)) {
                $this->appendEnumColumn(
                    $columns,
                    $fields,
                    $filters,
                    $imports,
                    $name,
                    $qualified,
                    $required,
                    $this->defaultEnumOptions($name),
                );

                continue;
            }

            if (in_array($type, ['bool', 'boolean', 'tinyint'], true)) {
                $columns[] = "BadgeColumn::make('{$name}')->from('{$qualified}')"
                    ."->colors(['1' => 'success', '' => 'neutral'])";
                $fields[] = "ToggleField::make('{$name}')";
                $filters[] = "BooleanFilter::make('{$name}')->column('{$qualified}')";
                $imports['BadgeColumn'] = 'Columns\BadgeColumn';
                $imports['ToggleField'] = 'Fields\ToggleField';
                $imports['BooleanFilter'] = 'Filters\BooleanFilter';

                continue;
            }

            if (in_array($type, ['int', 'integer', 'bigint', 'smallint', 'decimal', 'numeric', 'float', 'double'], true)) {
                $columns[] = "TextColumn::make('{$name}')->from('{$qualified}')->sortable()";
                $fields[] = "NumberField::make('{$name}'){$required}";
                $imports['TextColumn'] = 'Columns\TextColumn';
                $imports['NumberField'] = 'Fields\NumberField';

                continue;
            }

            if (in_array($type, ['text', 'longtext', 'mediumtext', 'json', 'jsonb'], true)) {
                $columns[] = "TextColumn::make('{$name}')->from('{$qualified}')->muted()";
                $fields[] = "TextareaField::make('{$name}'){$required}";
                $imports['TextColumn'] = 'Columns\TextColumn';
                $imports['TextareaField'] = 'Fields\TextareaField';

                continue;
            }

            $locked = $columns === [] ? '->locked()' : '';
            $columns[] = "TextColumn::make('{$name}')->from('{$qualified}')->sortable()->searchable(){$locked}";
            $fields[] = "TextField::make('{$name}'){$required}";
            $imports['TextColumn'] = 'Columns\TextColumn';
            $imports['TextField'] = 'Fields\TextField';
        }

        if ($softDeletes) {
            $filters[] = 'TrashedFilter::make(\'trashed\')';
            $imports['TrashedFilter'] = 'Filters\TrashedFilter';
        }

        return [
            'columns' => $this->stringList($columns),
            'fields' => $this->stringList($fields),
            'filters' => $this->stringList($filters),
            'imports' => $this->stringList($imports),
            'softDeletes' => $softDeletes,
            'hasMany' => $this->detectChildModels($table),
        ];
    }

    /**
     * @param  array<string, string>  $casts
     * @return list<string>
     */
    private function enumOptions(string $name, string $rawType, array $casts): array
    {
        if (preg_match_all("/'([^']+)'/", $rawType, $matches) > 0) {
            return $matches[1];
        }

        $cast = $casts[$name] ?? null;

        if (! is_string($cast) || ! enum_exists($cast)) {
            return [];
        }

        if (is_subclass_of($cast, \BackedEnum::class)) {
            return array_map(static fn (\BackedEnum $case): string => (string) $case->value, $cast::cases());
        }

        return array_map(static fn (\UnitEnum $case): string => $case->name, $cast::cases());
    }

    /**
     * @param array<int|string, mixed> $columns
     * @param array<int|string, mixed> $fields
     * @param array<int|string, mixed> $filters
     * @param array<int|string, mixed> $imports
     * @param list<string> $enumOptions
     */
    private function appendEnumColumn(
        array &$columns,
        array &$fields,
        array &$filters,
        array &$imports,
        string $name,
        string $qualified,
        string $required,
        array $enumOptions,
    ): void {
        $optionsCode = collect($enumOptions)
            ->map(static fn (string $value): string => "'{$value}' => '".str($value)->headline()->value()."'")
            ->implode(', ');
        $colors = collect($enumOptions)
            ->values()
            ->map(static fn (string $value, int $index): string => "'{$value}' => '".(['neutral', 'warning', 'success', 'danger'][$index % 4])."'")
            ->implode(', ');

        $columns[] = "BadgeColumn::make('{$name}')->from('{$qualified}')->sortable()"
            ."->colors([{$colors}])";
        $fields[] = "SelectField::make('{$name}'){$required}->options([{$optionsCode}])";
        $filters[] = "SelectFilter::make('{$name}')->column('{$qualified}')->options(["
            .collect($enumOptions)->map(static fn (string $v): string => "'{$v}'")->implode(', ')
            .'])';
        $imports['BadgeColumn'] = 'Columns\BadgeColumn';
        $imports['SelectField'] = 'Fields\SelectField';
        $imports['SelectFilter'] = 'Filters\SelectFilter';
    }

    /**
     * @param array<int|string, mixed> $values
     * @return list<string>
     */
    private function stringList(array $values): array
    {
        $result = [];

        foreach ($values as $value) {
            if (is_string($value)) {
                $result[] = $value;
            }
        }

        return $result;
    }

    private function isLikelyEnumColumn(string $name, string $type): bool
    {
        return in_array($name, ['status', 'type', 'state'], true)
            && in_array($type, ['varchar', 'string', 'char'], true);
    }

    /** @return list<string> */
    private function defaultEnumOptions(string $name): array
    {
        return match ($name) {
            'status' => ['draft', 'published', 'archived'],
            'type' => ['default', 'custom'],
            'state' => ['open', 'closed'],
            default => ['option_a', 'option_b'],
        };
    }

    /** @return class-string<Model>|null */
    private function inferRelatedModel(string $column): ?string
    {
        if (! str_ends_with($column, '_id')) {
            return null;
        }

        $base = Str::studly(Str::beforeLast($column, '_id'));

        foreach ([$base, Str::studly(Str::singular($base))] as $studly) {
            $class = "App\\Models\\{$studly}";

            if (class_exists($class) && is_subclass_of($class, Model::class)) {
                return $class;
            }
        }

        return null;
    }

    /** @param  class-string<Model>  $modelClass */
    private function inferTitleAttribute(string $modelClass): string
    {
        $relatedTable = (new $modelClass)->getTable();

        foreach (['name', 'title', 'email', 'number', 'label'] as $attribute) {
            if (Schema::hasColumn($relatedTable, $attribute)) {
                return $attribute;
            }
        }

        return 'id';
    }

    /** @return list<string> */
    private function detectChildModels(string $table): array
    {
        $foreignKey = Str::snake(Str::singular($table)).'_id';
        $children = [];

        foreach (Schema::getTableListing() as $candidate) {
            $name = str_contains($candidate, '.') ? Str::after($candidate, '.') : $candidate;

            if ($name === $table || ! Schema::hasColumn($name, $foreignKey)) {
                continue;
            }

            $children[] = Str::studly(Str::singular($name));
        }

        sort($children);

        return $children;
    }

    /** @return array{columns: list<string>, fields: list<string>, filters: list<string>, imports: list<string>, softDeletes: bool, hasMany: list<string>} */
    private function placeholders(): array
    {
        return [
            'columns' => ["TextColumn::make('name')->sortable()->searchable()->locked()"],
            'fields' => ["TextField::make('name')->required()"],
            'filters' => [],
            'imports' => ['Columns\TextColumn', 'Fields\TextField'],
            'softDeletes' => false,
            'hasMany' => [],
        ];
    }

    /**
     * @param  list<string>  $columns
     * @param  list<string>  $fields
     * @param  list<string>  $filters
     * @param  list<string>  $imports
     * @param  list<string>  $hasMany
     */
    private function render(
        string $model,
        string $modelClass,
        array $columns,
        array $fields,
        array $filters,
        array $imports,
        string $panelId,
        string $namespace,
        bool $softDeletes,
        array $hasMany,
    ): string {
        $panelImports = collect($imports)
            ->reject(static fn (string $i): bool => str_starts_with($i, 'Models\\'))
            ->map(static function (string $i): string {
                if (str_starts_with($i, 'Columns')) {
                    return 'use Alxtexh\\Panel\\Tables\\'.$i.';';
                }

                if (str_starts_with($i, 'Filters')) {
                    return 'use Alxtexh\\Panel\\Tables\\'.$i.';';
                }

                return 'use Alxtexh\\Panel\\Forms\\'.$i.';';
            });

        $modelImports = collect($imports)
            ->filter(static fn (string $i): bool => str_starts_with($i, 'Models\\'))
            ->map(static fn (string $i): string => 'use App\\'.$i.';');

        $use = $panelImports->merge($modelImports)->sort()->implode("\n");

        $table = (new $modelClass)->getTable();
        $columnCode = collect($columns)->map(static fn (string $c): string => "                {$c},")->implode("\n");
        $fieldCode = collect($fields)->map(static fn (string $f): string => "            {$f},")->implode("\n");
        $filterCode = $filters === []
            ? ''
            : "\n                    ->filters([\n"
                .collect($filters)->map(static fn (string $f): string => "                        {$f},")->implode("\n")
                ."\n                    ])";
        $foreignKey = Str::snake(Str::singular($table)).'_id';
        $hasManyBlock = $hasMany === []
            ? ''
            : "\n            /*\n             * HasMany children detected on `{$foreignKey}`:\n"
                .collect($hasMany)->map(static fn (string $child): string => "             *     php artisan make:panel-relation-manager {$model} {$child}")->implode("\n")
                ."\n             */";
        $softDeleteNote = $softDeletes
            ? "\n         * Soft deletes: `TrashedFilter` is wired on the table."
            : '';

        return <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        use {$modelClass};
        {$use}
        use Alxtexh\\Panel\\Forms\\Form;
        use Alxtexh\\Panel\\Resources\\Resource;
        use Alxtexh\\Panel\\Tables\\Table;

        /**
         * Generated by `make:panel-resource {$model}`.
         *
         * Edit freely - this is a starting point, not a contract. Discovery picks
         * it up automatically, so there is nothing to register.
         *
         * `tenant_id` is deliberately absent from the form. It is set from request
         * context, and a field for it would be a way to write into another tenant.{$softDeleteNote}
         */
        final class {$model}Resource extends Resource
        {
            protected static string \$model = {$model}::class;

            /*
             * WHICH PANEL THIS BELONGS TO, and therefore where it is reachable.
             * Only this panel's routes resolve it: a resource is not visible -
             * or addressable - from another portal, which is the isolation the
             * panel split exists for rather than a naming convention.
             */
            protected static string \$panel = '{$panelId}';
            {$hasManyBlock}

            public static function form(Form \$form): Form
            {
                return \$form->columns(2)->schema([
        {$fieldCode}
                ]);
            }

            public static function table(Table \$table): Table
            {
                return \$table
                    ->columns([
        {$columnCode}
                    ]){$filterCode}
                    ->keyColumn('{$table}.id')
                    ->alsoSelect(['{$table}.id'])
                    /*
                     * ROW AND BULK ACTIONS ARE NOT GENERATED, because what may
                     * be DONE to a {$model} is the one thing a table cannot be
                     * read off. Uncomment into this chain and edit:
                     *
                     * ->recordActions([
                     *     RecordAction::make('suspend', 'Suspend')
                     *         ->authorize('update')
                     *         ->confirm('Suspend this {$model}?')
                     *         ->mutate(['status' => 'suspended']),
                     *
                     *     // ASKING FOR SOMETHING FIRST is `->form()`. The modal
                     *     // opens with no request - the schema travels with the
                     *     // action - so do NOT write a screen for this.
                     *     RecordAction::make('note', 'Add a note')
                     *         ->authorize('update')
                     *         ->form(fn (Form \$form): Form => \$form->schema([
                     *             TextareaField::make('note')->required()->rule('max:280'),
                     *         ]))
                     *         ->handle(fn ({$model} \$record, array \$data) => \$record
                     *             ->notes()->create(\$data)),
                     * ])
                     * ->bulkActions([
                     *     // The same `->form()` works here and is asked ONCE for
                     *     // the whole selection; the handler runs once per chunk
                     *     // with the same values.
                     *     BulkAction::make('suspend', 'Suspend selected')
                     *         ->authorize('update')
                     *         ->mutate(['status' => 'suspended']),
                     * ])
                     *
                     * `->form()` PAIRS WITH `->handle()`, NEVER `->mutate()` - a
                     * mutation is fixed at definition time and has nowhere to
                     * put what somebody typed, and declaring both throws. The
                     * declared FIELDS are the allow-list: the endpoint validates
                     * against them and drops every key they do not name.
                     *
                     * `->authorize()` NAMES A POLICY METHOD, and an action
                     * without one is refused rather than permitted.
                     *
                     * IMPORT WHAT YOU UNCOMMENT - they are not imported above,
                     * because an import for code nobody wrote yet is one every
                     * linter deletes:
                     *
                     *     use Alxtexh\Panel\Actions\BulkAction;
                     *     use Alxtexh\Panel\Actions\RecordAction;
                     *     use Alxtexh\Panel\Forms\Fields\TextareaField;
                     */
                    ->defaultSort('created_at', 'desc');
            }
        }

        PHP;
    }
}
