<?php

declare(strict_types=1);

namespace App\Panel\Reseller\Resources;

use App\Models\Plan;
use Alxtexh\Panel\Actions\RecordAction;
use Alxtexh\Panel\Forms\Fields\NumberField;
use Alxtexh\Panel\Forms\Fields\TextareaField;
use Alxtexh\Panel\Forms\Fields\TextField;
use Alxtexh\Panel\Forms\Fields\ToggleField;
use Alxtexh\Panel\Forms\Form;
use Alxtexh\Panel\Resources\Resource;
use Alxtexh\Panel\Tables\Columns\BadgeColumn;
use Alxtexh\Panel\Tables\Columns\DateColumn;
use Alxtexh\Panel\Tables\Columns\TextColumn;
use Alxtexh\Panel\Tables\Table;

/**
 * Generated by `make:panel-resource Plan`.
 *
 * Edit freely - this is a starting point, not a contract. Discovery picks
 * it up automatically, so there is nothing to register.
 *
 * `tenant_id` is deliberately absent from the form. It is set from request
 * context, and a field for it would be a way to write into another tenant.
 */
final class PlanResource extends Resource
{
    protected static string $model = Plan::class;

    protected static ?string $purpose = 'The plans this reseller offers to their own subscribers.';

    /*
     * WHICH PANEL THIS BELONGS TO, and therefore where it is reachable.
     * Only this panel's routes resolve it: a resource is not visible -
     * or addressable - from another portal, which is the isolation the
     * panel split exists for rather than a naming convention.
     */
    protected static string $panel = 'reseller';

    /**
     * A DISTINCT KEY, because the operator portal already has a `plans`.
     *
     * Keys are unique across the whole installation, not per panel - they are
     * the URL segment, the ability suffix (`view_any_reseller-plans`), the
     * schema-cache component and the audit label, and making them unique only
     * within a panel would mean every one of those needed a panel qualifier too.
     * The registry refuses a collision rather than letting one resource silently
     * overwrite the other, which is what it used to do.
     */
    public static function key(): string
    {
        return 'reseller-plans';
    }

    public static function form(Form $form): Form
    {
        return $form->columns(2)->schema([
            TextField::make('name')->required(),
            NumberField::make('speed_mbps')->required(),
            NumberField::make('price_cents')->required(),
            ToggleField::make('is_active'),
            NumberField::make('position')->required(),
            TextareaField::make('custom'),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            // Browsed, then opened - see ClientResource's own note on why
            // this is declared per resource rather than default. rowClick
            // alone only arms the click; the row still needs a real 'view'
            // RecordAction below to have somewhere to send it.
            ->rowClick('view')
            ->recordActions([
                RecordAction::make('view', 'View')
                    ->icon('eye')
                    ->color('primary')
                    ->authorize('view')
                    ->link(fn (array $row): string => '/reseller/reseller-plans/'.$row['id']),
            ])
            ->columns([
                TextColumn::make('name')->from('plans.name')->sortable()->searchable()->locked(),
                TextColumn::make('speed_mbps')->from('plans.speed_mbps')->sortable(),
                TextColumn::make('price_cents')->from('plans.price_cents')->sortable(),
                BadgeColumn::make('is_active')->from('plans.is_active')->colors(['1' => 'success', '' => 'neutral']),
                DateColumn::make('created_at')->from('plans.created_at')->sortable()->withTime()->muted(),
                DateColumn::make('updated_at')->from('plans.updated_at')->sortable()->withTime()->muted(),
                TextColumn::make('position')->from('plans.position')->sortable(),
                TextColumn::make('custom')->from('plans.custom')->muted(),
            ])
            ->keyColumn('plans.id')
            ->alsoSelect(['plans.id'])
            ->defaultSort('created_at', 'desc');
    }
}
